version: "3.7"

services:
  app:
    image: client
    working_dir: /client
    volumes:
      - ./:/app
    ports:
      - 4200:4200
    # --host 0.0.0.0 to listen to all the interfaces from the container (dev env)
    command: >
      sh -c "npm install &&
             npx ng serve --host 0.0.0.0"
            
  server:
    image: server:lts-alpine
    working_dir: /server
    volumes:
      - ./server:/server
    # port 3000 has to match src/proxy.conf.json
    ports:
      - 4000:4000
    command: >
      sh -c "npm i -g nodemon && npm install && nodemon ./bin/www"


