version: "3.7"

services:
  angular:
    image: node:lts-alpine
    working_dir: /client
    volumes:
     - ./client:/client
     - ./client/node_modules:/client/node_modules

    ports:
      - 4200:4200
    # --host 0.0.0.0 to listen to all the interfaces from the container (dev env)
    command: >
      sh -c "npm install &&
             npx ng serve --host 0.0.0.0"

  express:
    image: node:lts-alpine
    working_dir: /server
    volumes:
      - ./server:/server
      - ./server/node_modules:/server/node_modules
  
    
    # port 3000 has to match src/proxy.conf.json
    ports:
      - 5000:5000

    command: >
      sh -c "npm i -g nodemon && npm install && nodemon ./bin/www"


